### ISSUE TITLE
Incluir Tratamentos de Exceção

### ISSUE THREAD

**Issue by caburu** [ufla-ppoo/AgenciaBancaria#1]
Esse projeto é o código-base inicial usado para apresentar os exemplos de Tratamentos de Exceção nos slides sobre o assunto. Mas seria interessante na verdade disponibilizar o projeto com as alterações da aula, pois assim seria um código de exemplo sobre Tratamentos de Exceção.

**Comment by ValterGNeto** [comment]
Boa tarde, tenho interesse em desenvolver essa issue, mas fiquei em dúvida sobre as "alterações da aula" que devem ser disponibilizadas no projeto. Quais seriam essas alterações?

**Comment by caburu** [comment]
Olá @ValterGNeto, bacana que está disposto a colaborar!

As alterações estão descritas nesta [apresentação de slides](https://docs.google.com/presentation/d/1hffEwyq0RrZggLlD-BOWN9uEIebh3yWBhkStcy9vNuw/edit?usp=sharing). A ideia é que o projeto tenha todas as alterações feitas durante a aula para ficar como exemplo para os alunos (inclusive as do slide 22, por exemplo).

- Obs.: sobre a classe `SaldoInsuficienteException`, ela deve ser mantida como exceção não verificada. Nos slides eu mudo para exceção verificada apenas para demonstrar as consequências.

Como é um projeto bem simples, não há um procedimento formal para contribuições. Mas, para mantermos as coisas organizadas, seria bom que enviasse a solução da issue na forma de um Pull Request para que eu possa comentar/avaliar a solução.

Qualquer dúvida adicional quanto ao projeto, aos slides, ou à issue em si, estou à disposição.

**Comment by ValterGNeto** [comment]
Perfeito. Assim que eu concluir a issue abro o Pull Request
